# Generated by Django 6.0.4 on 2026-04-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('semester', models.IntegerField(default=1)),
                ('max_marks', models.IntegerField(default=100)),
                ('credits', models.IntegerField(default=4)),
            ],
            options={
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(db_index=True, max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField(default=1)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=1)),
                ('cleared', models.BooleanField(default=False)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['usn', 'semester'],
                'unique_together': {('usn', 'subject_code', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='NBAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('semester', models.IntegerField(default=1)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('appeared', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('total_enrolled', models.IntegerField(default=0)),
                ('mean_sgpa', models.FloatField(default=0.0)),
                ('si', models.FloatField(default=0.0, verbose_name='Success Index')),
                ('api', models.FloatField(default=0.0, verbose_name='Academic Performance Index')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('subject_code', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(db_index=True, max_length=20)),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_code', models.CharField(db_index=True, max_length=20)),
                ('subject_name', models.CharField(blank=True, max_length=200, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('max_marks', models.FloatField(default=100)),
                ('grade', models.CharField(blank=True, choices=[('O', 'Outstanding (≥90)'), ('A+', 'Excellent (80-89)'), ('A', 'Very Good (70-79)'), ('B+', 'Good (60-69)'), ('B', 'Average (55-59)'), ('C', 'Satisfactory (50-54)'), ('P', 'Pass (40-49)'), ('F', 'Fail (<40)'), ('AB', 'Absent')], max_length=5, null=True)),
                ('sgpa', models.FloatField(blank=True, null=True)),
                ('semester', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('GM', 'General Merit'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('OTHER', 'Other')], default='GM', max_length=10)),
                ('admission_quota', models.CharField(choices=[('CET', 'CET'), ('COMED_K', 'COMED-K'), ('MANAGEMENT', 'Management'), ('NRI', 'NRI'), ('OTHER', 'Other')], default='CET', max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_pass', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analytics.subject')),
            ],
            options={
                'ordering': ['usn', 'semester', 'subject_code'],
                'indexes': [models.Index(fields=['subject_code', 'semester'], name='analytics_r_subject_ac93b1_idx'), models.Index(fields=['category'], name='analytics_r_categor_5ca064_idx'), models.Index(fields=['usn'], name='analytics_r_usn_8091e2_idx')],
            },
        ),
    ]
